name: run-scraping

on:
  schedule:
    - cron: '0 6 * * *' # Ejecutar todos los días a las 06:00 UTC
  workflow_dispatch:

jobs:
  scraping-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 selenium webdriver-manager chromedriver-binary-auto

    - name: Run sunatusd_pen script
      run: python sunatusd_pen.py
